name: eTorch CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: eiffel/eiffel:latest
      options: --user root
    
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - uses: actions/checkout@v4
    
    - name: Install System Dependencies
      run: |
        apt-get update
        apt-get install -y libopenblas-dev
    
    - name: Compile the core library
      run: |
        # Set up a fake X server just in case the compiler prompts despite being in terminal
        export DISPLAY=:99
        ec -config etorch.ecf -target etorch -clean -c_compile -batch
        
    - name: Run AutoTests
      run: |
        export DISPLAY=:99
        ec -config etorch.ecf -target tests -clean -c_compile -finalize -tests -batch

    - name: Run Use Cases
      run: |
        export DISPLAY=:99
        ec -config etorch.ecf -target use_cases -clean -c_compile -finalize -batch
        ./EIFGENs/use_cases/F_code/etorch
