name: eTorch CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: eiffel/eiffel:latest
      options: --user root
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Compile the core library
      run: |
        # Set up a fake X server just in case the compiler prompts despite being in terminal
        export DISPLAY=:99
        ec -config etorch.ecf -target etorch -clean -c_compile -batch
        
    - name: Run Tests
      run: |
        export DISPLAY=:99
        ec -config etorch.ecf -target tests -clean -c_compile -finalize -tests -batch
